name: dotnet
on:
  push:
    branches: develop

    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: app/SampleWebApp

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy Artifacts
      run: mkdir artifacts && cp /home/runner/work/dotnetapp/dotnetapp/app/SampleWebApp/bin/Debug/net5.0/*.dll artifacts
  
      
    - uses: aws-actions/configure-aws-credentials@v1
      name: Upload to S3

    
      with:
        command: cp
        source: artifacts
        destination: s3://artifactbucket8978/folder
        aws-region: 'ap-south-1'
        aws-access-key-id: 'AKIA5UQQIXW63FYQ5CXV'
        aws-secret-access-key: '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'  
